// Autogenerated from epoc32/build/sipfw/c_867e51e00fcbdf36/sipcodec_dll/sipstrconsts.st by the stringtable tool - Do not edit

#ifndef STRINGTABLE_SipStrConsts
#define STRINGTABLE_SipStrConsts

#include <stringpool.h>

struct TStringTable;

/**
 * @publishedAll
 * @released
*/
class SipStrConsts 
	{
public:
	enum TStrings
		{
		// General constants
		/**  */
		EEmpty,
		/** SIP */
		ESIP,
		/** sip */
		ESip,
		/** sips */
		ESips,
		/** 2.0 */
		EDefaultVersionNumber,
		/** SIP/2.0 */
		EDefaultProtocolVersion,
		/** UDP */
		EUDP,
		/** udp */
		EUdp,
		/** TCP */
		ETCP,
		/** tcp */
		ETcp,
		/** localhost */
		ELocalHost,
		// SIP methods
		/** REGISTER */
		ERegister,
		/** INVITE */
		EInvite,
		/** CANCEL */
		ECancel,
		/** ACK */
		EAck,
		/** BYE */
		EBye,
		/** PRACK */
		EPrack,
		/** UPDATE */
		EUpdate,
		/** SUBSCRIBE */
		ESubscribe,
		/** NOTIFY */
		ENotify,
		/** REFER */
		ERefer,
		/** MESSAGE */
		EMessage,
		/** OPTIONS */
		EOptions,
		/** INFO */
		EInfo,
		// SIP reason phrases:
		/** OK */
		EPhraseOk,
		/** Trying */
		EPhraseTrying,
		/** Ringing */
		EPhraseRinging,
		/** Session Progress */
		EPhraseSessionProgress,
		/** Bad Request */
		EPhraseBadRequest,
		/** Unauthorized */
		EPhraseUnauthorized,
		/** Forbidden */
		EPhraseForbidden,
		/** Not Found */
		EPhraseNotFound,
		/** Method Not Allowed */
		EPhraseMethodNotAllowed,
		/** Proxy Authentication Required */
		EPhraseProxyAuthenticationRequired,
		/** Request Timeout */
		EPhraseRequestTimeout,
		/** Unsupported Media Type */
		EPhraseUnsupportedMediaType,
		/** Unsupported URI Scheme */
		EPhraseUnsupportedURIScheme,
		/** Bad Extension */
		EPhraseBadExtension,
		/** Extension Required */
		EPhraseExtensionRequired,
		/** Interval Too Brief */
		EPhraseIntervalTooBrief,
		/** Temporarily Not Available */
		EPhraseTemporarilyNotAvailable,
		/** Call/Transaction Does Not Exist */
		EPhraseCallTransactionDoesNotExist,
		/** Loop Detected */
		EPhraseLoopDetected,
		/** Too Many Hops */
		EPhraseTooManyHops,
		/** Busy Here */
		EPhraseBusyHere,
		/** Request Terminated */
		EPhraseRequestTerminated,
		/** Not Acceptable Here */
		EPhraseNotAcceptableHere,
		/** Bad Event */
		EPhraseBadEvent,
		/** Security Agreement Required */
		EPhraseSecurityAgreementRequired,
		/** Server Internal Error */
		EPhraseServerInternalError,
		/** Service Unavailable */
		EPhraseServiceUnavailable,
		/** Version Not Supported */
		EPhraseVersionNotSupported,
		/** Decline */
		EPhraseDecline,
		// SIP parameters:
		/** ttl */
		ETtl,
		/** maddr */
		EMaddr,
		/** received */
		EReceived,
		/** branch */
		EBranch,
		/** q */
		EQ,
		/** expires */
		EExpires,
		/** tag */
		ETag,
		/** transport */
		ETransport,
		/** user */
		EUser,
		/** method */
		EMethod,
		/** lr */
		ELr,
		/** d-alg */
		EDigestAlgorithm,
		/** d-qop */
		EDigestQop,
		/** d-ver */
		EDigestVerify,
		/** handling */
		EHandling,
		/** reason */
		EReason,
		/** retry-after */
		ERetryAfter,
		/** id */
		EId,
		/** nextnonce */
		ENextNonce,
		/** qop */
		EQop,
		/** rspauth */
		EResponseAuth,
		/** cnonce */
		ECNonce,
		/** nc */
		ENonceCount,
		/** realm */
		ERealm,
		/** domain */
		EDomain,
		/** nonce */
		ENonce,
		/** opaque */
		EOpaque,
		/** stale */
		EStale,
		/** algorithm */
		EAlgorithm,
		/** username */
		EUserName,
		/** uri */
		EUri,
		/** response */
		EResponse,
		/** comp */
		EComp,
		/** sigcomp */
		ESigComp,
		/** sec-agree */
		ESecAgreeTag,
		/** duration */
		EDuration,
		/** audio */
		EAudio,
		/** automata */
		EAutomata,
		/** class */
		EClass,
		/** duplex */
		EDuplex,
		/** data */
		EData,
		/** control */
		EControl,
		/** mobility */
		EMobility,
		/** description */
		EDescription,
		/** events */
		EEvents,
		/** priority */
		EPriority,
		/** methods */
		EMethods,
		/** schemes */
		ESchemes,
		/** application */
		EApplication,
		/** video */
		EVideo,
		/** language */
		ELanguage,
		/** type */
		EType,
		/** isfocus */
		EIsfocus,
		/** actor */
		EActor,
		/** text */
		EText,
		/** extensions */
		EExtensions,
		/** require */
		ERequire,
		/** explicit */
		EExplicit,
		/** cgi-3gpp */
		ECgi3gpp,
		/** utran-cell-id-3gpp */
		EUtranCellId3gpp,
		/** auts */
		EAuts,
		// SIP header names:
		/** To */
		EToHeader,
		/** t */
		EToHeaderCompact,
		/** From */
		EFromHeader,
		/** f */
		EFromHeaderCompact,
		/** CSeq */
		ECSeqHeader,
		/** Call-ID */
		ECallIDHeader,
		/** i */
		ECallIDHeaderCompact,
		/** Content-Length */
		EContentLengthHeader,
		/** l */
		EContentLengthHeaderCompact,
		/** Via */
		EViaHeader,
		/** v */
		EViaHeaderCompact,
		/** Route */
		ERouteHeader,
		/** Record-Route */
		ERecordRouteHeader,
		/** Service-Route */
		EServiceRouteHeader,
		/** Contact */
		EContactHeader,
		/** m */
		EContactHeaderCompact,
		/** Content-Type */
		EContentTypeHeader,
		/** c */
		EContentTypeHeaderCompact,
		/** Expires */
		EExpiresHeader,
		/** Min-Expires */
		EMinExpiresHeader,
		/** Max-Forwards */
		EMaxForwardsHeader,
		/** Allow */
		EAllowHeader,
		/** Proxy-Require */
		EProxyRequireHeader,
		/** Require */
		ERequireHeader,
		/** Supported */
		ESupportedHeader,
		/** k */
		ESupportedHeaderCompact,
		/** Unsupported */
		EUnsupportedHeader,
		/** Content-Encoding */
		EContentEncodingHeader,
		/** e */
		EContentEncodingHeaderCompact,
		/** Refer-To */
		EReferToHeader,
		/** r */
		EReferToHeaderCompact,
		/** Security-Client */
		ESecurityClientHeader,
		/** Security-Server */
		ESecurityServerHeader,
		/** Security-Verify */
		ESecurityVerifyHeader,
		/** Authentication-Info */
		EAuthenticationInfoHeader,
		/** Accept */
		EAcceptHeader,
		/** Accept-Encoding */
		EAcceptEncodingHeader,
		/** Accept-Language */
		EAcceptLanguageHeader,
		/** Content-Disposition */
		EContentDispositionHeader,
		/** Subscription-State */
		ESubscriptionStateHeader,
		/** Allow-Events */
		EAllowEventsHeader,
		/** u */
		EAllowEventsHeaderCompact,
		/** Event */
		EEventHeader,
		/** o */
		EEventHeaderCompact,
		/** Authorization */
		EAuthorizationHeader,
		/** Proxy-Authenticate */
		EProxyAuthenticateHeader,
		/** Proxy-Authorization */
		EProxyAuthorizationHeader,
		/** WWW-Authenticate */
		EWWWAuthenticateHeader,
		/** Reply-To */
		EReplyToHeader,
		/** RAck */
		ERAckHeader,
		/** RSeq */
		ERSeqHeader,
		/** Timestamp */
		ETimestampHeader,
		/** Retry-After */
		ERetryAfterHeader,
		/** Accept-Contact */
		EAcceptContactHeader,
		/** a */
		EAcceptContactHeaderCompact,
		/** P-Associated-URI */
		EPAssociatedURIHeader,
		/** P-Access-Network-Info */
		EPAccessNetworkInfoHeader,
		// SIP reason phrases:
		/** Not Implemented */
		EPhraseNotImplemented,
		// TLS transport for Via-header
		/** TLS */
		ETLS,
		// Algorithms supported by SIPSec Digest plugin
		/** MD5 */
		EMD5,
		/** AKAv1-MD5 */
		EAKAv1MD5,
		// rport parameter
		/** rport */
		ERport
		};
	static const TStringTable Table;	
	};

#endif // STRINGTABLE_SipStrConsts

