// Autogenerated from epoc32/build/smilparser/c_8a52abcb1170709b/smildtd_dll/smilgenericelements.st by the stringtable tool - Do not edit

#ifndef STRINGTABLE_SMILGenericElements
#define STRINGTABLE_SMILGenericElements

#include <stringpool.h>

struct TStringTable;

/** 
An Example String Table
@publishedAll
@released
*/ 
class SMILGenericElements 
	{
public:
	enum TStrings
		{
		/** anchor anchorBase */
		EAnchorBase,
		/** animation media */
		EAnimationBase,
		/** area anchorBase */
		EAreaBase,
		/** audio media */
		EAudioBase,
		/** img media */
		EImgBase,
		/** par timing */
		EParBase,
		/** ref media */
		ERefBase,
		/** seq timing */
		ESeqBase,
		/** text media */
		ETextBase,
		/** textstream media */
		ETextstreamBase,
		/** video media */
		EVideoBase
		};
	static const TStringTable Table;	
	};

#endif // STRINGTABLE_SMILGenericElements

