// Autogenerated from epoc32/build/smilparser/c_8a52abcb1170709b/smildtd_dll/smilelements.st by the stringtable tool - Do not edit

#ifndef STRINGTABLE_SMILElements
#define STRINGTABLE_SMILElements

#include <stringpool.h>

struct TStringTable;

/** 
An Example String Table
@publishedAll
@released
*/
class SMILElements 
	{
public:
	enum TStrings
		{
		/** a */
		Ea,
		/** anchor */
		EAnchor,
		/** animate */
		EAnimate,
		/** animateColor */
		EAnimateColor,
		/** animateMotion */
		EAnimateMotion,
		/** animation */
		EAnimation,
		/** area */
		EArea,
		/** audio */
		EAudio,
		/** body */
		EBody,
		/** brush */
		EBrush,
		/** customAttributes */
		ECustomAttributes,
		/** customTest */
		ECustomTest,
		/** excl */
		EExcl,
		/** head */
		EHead,
		/** img */
		EImg,
		/** layout */
		ELayout,
		/** meta */
		EMeta,
		/** metadata */
		EMetadata,
		/** par */
		EPar,
		/** param */
		EParam,
		/** prefetch */
		EPrefetch,
		/** priorityClass */
		EpriorityClass,
		/** ref */
		ERef,
		/** region */
		ERegion,
		/** regPoint */
		ERegPoint,
		/** root-layout */
		ERootLayout,
		/** seq */
		ESeq,
		/** smil */
		ESmil,
		/** switch */
		ESwitch,
		/** text */
		EText,
		/** textstream */
		ETextstream,
		/** topLayout */
		ETopLayout,
		/** transition */
		ETransition,
		/** transitionFilter */
		ETransitionFilter,
		/** video */
		EVideo
		};
	static const TStringTable Table;	
	};

#endif // STRINGTABLE_SMILElements

