// Autogenerated from epoc32/build/smilparser/c_8a52abcb1170709b/smildtd_dll/smilattributes.st by the stringtable tool - Do not edit

#ifndef STRINGTABLE_SMILAttributes
#define STRINGTABLE_SMILAttributes

#include <stringpool.h>

struct TStringTable;

/** 
An Example String Table
@publishedAll
@released
*/ 
class SMILAttributes 
	{
public:
	enum TStrings
		{
		/** a accesskey */
		EAAccessKey,
		/** a actuate onLoad onRequest */
		EAActuate,
		/** a alt */
		EAAlt,
		/** a begin */
		EABegin,
		/** a class */
		EAClass,
		/** a destinationLevel */
		EADestinationLevel,
		/** a destinationPlaystate pause play stop */
		EADestinationPlaystate,
		/** a dur */
		EADur,
		/** a end */
		EAEnd,
		/** a external false true */
		EAExternal,
		/** a fill freeze hold remove transition */
		EAFill,
		/** a href */
		EAHref,
		/** a id */
		EAId,
		/** a max */
		EAMax,
		/** a min */
		EAMin,
		/** a repeatCount */
		EARepeatCount,
		/** a repeatDur */
		EARepeatDur,
		/** a show new pause replace */
		EAShow,
		/** a sourceLevel */
		EASourceLevel,
		/** a sourcePlaystate pause play stop */
		EASourcePlaystate,
		/** a tabindex */
		EATabIndex,
		/** a target */
		EATarget,
		/** a title */
		EATitle,
		/** a xml:lang */
		EAXMLLang,
		/** anchorBase accesskey */
		EAnchorBaseAccessKey,
		/** anchorBase actuate onLoad onRequest */
		EAnchorBaseActuate,
		/** anchorBase alt */
		EAnchorBaseAlt,
		/** anchorBase begin */
		EAnchorBaseBegin,
		/** anchorBase class */
		EAnchorBaseClass,
		/** anchorBase coords */
		EAnchorBaseCoOrds,
		/** anchorBase destinationLevel */
		EAnchorBaseDestLevel,
		/** anchorBase destinationPlaystate pause play stop */
		EAnchorBaseDestinationPlaystate,
		/** anchorBase dur */
		EAnchorBaseDur,
		/** anchorBase end */
		EAnchorBaseEnd,
		/** anchorBase endsync */
		EAnchorBaseEndsync,
		/** anchorBase external false true */
		EAnchorBaseExternal,
		/** anchorBase fill hold freeze remove transition */
		EAnchorBaseFill,
		/** anchorBase href */
		EAnchorBaseHRef,
		/** anchorBase id */
		EAnchorBaseId,
		/** anchorBase max */
		EAnchorBaseMax,
		/** anchorBase min */
		EAnchorBaseMin,
		/** anchorBase nohref nohref */
		EAnchorBase,
		/** anchorBase repeat */
		EAnchorBaseRepeat,
		/** anchorBase repeatCount */
		EAnchorBaseRepeatCnt,
		/** anchorBase repeatDur */
		EAnchorBaseRepeatDur,
		/** anchorBase shape circle default poly rect */
		EAnchorBaseShape,
		/** anchorBase show new pause replace */
		EAnchorBaseShow,
		/** anchorBase skip-content false true */
		EAnchorBaseSkipContent,
		/** anchorBase sourceLevel */
		EAnchorBaseSourceLev,
		/** anchorBase sourcePlaystate pause play stop */
		EAnchorBaseSourcePlaystate,
		/** anchorBase tabindex */
		EAnchorBaseTabIndex,
		/** anchorBase target */
		EAnchorBaseTarget,
		/** anchorBase title */
		EAnchorBaseTitle,
		/** anchorBase xml:lang */
		EAnchorBaseXMLLang,
		/** body class */
		EBodyClass,
		/** body id */
		EBodyId,
		/** body title */
		EBodyTitle,
		/** body xml:lang */
		EBodyXMLLang,
		/** head class */
		EHeadClass,
		/** head id */
		EHeadId,
		/** head title */
		EHeadTitle,
		/** head xml:lang */
		EHeadXMLLang,
		/** layout class */
		ELayoutClass,
		/** layout id */
		ELayoutId,
		/** layout systemAudioDesc off on */
		ELayoutSysAudioDesc,
		/** layout systemBitrate */
		ELayoutSysBitrate,
		/** layout systemCPU */
		ELayoutSysCPU,
		/** layout systemCaptions off on */
		ELayoutSysCaptions,
		/** layout systemComponent */
		ELayoutSysComp,
		/** layout systemLanguage */
		ELayoutSysLang,
		/** layout systemOperatingSystem */
		ELayoutSysOS,
		/** layout systemOverdubOrSubtitle overdub subtitle */
		ELayoutSysOverCap,
		/** layout systemRequired */
		ELayoutSysReq,
		/** layout systemScreenDepth */
		ELayoutSysScrnDepth,
		/** layout systemScreenSize */
		ELayoutSysScrnSize,
		/** layout title */
		ELayoutTitle,
		/** layout type */
		ElayoutType,
		/** layout xml:lang */
		ELayoutXMLLang,
		/** media abstract */
		EMediaAbstract,
		/** media alt */
		EMediaAlt,
		/** media author */
		EMediaAuthor,
		/** media begin */
		EMediaBegin,
		/** media class */
		EMediaClass,
		/** media clip-begin */
		EMediaClipHypBegin,
		/** media clip-end */
		EMediaClipHypEnd,
		/** media clipBegin */
		EMediaClipBegin,
		/** media clipEnd */
		EMediaClipEnd,
		/** media copyright */
		EMediaCopyright,
		/** media customTest */
		EMediaCustomTest,
		/** media dur */
		EMediaDur,
		/** media end */
		EMediaEnd,
		/** media endsync */
		EMediaEndsync,
		/** media fill freeze hold remove transition */
		EMediaFill,
		/** media id */
		EMediaId,
		/** media longdesc */
		EMediaLongDesc,
		/** media max */
		EMediaMax,
		/** media min */
		EMediaMin,
		/** media readIndex */
		EMediaReadIndex,
		/** media region */
		EMediaRegion,
		/** media repeat */
		EMediaRepeat,
		/** media repeatCount */
		EMediaRepeatCount,
		/** media repeatDur */
		EMediaRepeatDur,
		/** media src */
		EMediaSrc,
		/** media system-bitrate */
		EMediaSysHypBitrate,
		/** media system-captions */
		EMediaSysHypCap,
		/** media system-language */
		EMediaSysHypLang,
		/** media system-overdub-or-caption caption overdub */
		EMediaSysHypOverCap,
		/** media system-required */
		EMediaSysHypReq,
		/** media system-screen-depth */
		EMediaSysHypScrnDepth,
		/** media system-screen-size */
		EMediaSysHypScrnSize,
		/** media systemAudioDesc off on */
		EMediaSysAudioDesc,
		/** media systemBitrate */
		EMediaSysBitrate,
		/** media systemCPU */
		EMediaSysCPU,
		/** media systemCaptions off on */
		EMediaSysCaptions,
		/** media systemComponent */
		EMediaSysComp,
		/** media systemLanguage */
		EMediaSysLang,
		/** media systemOperatingSystem */
		EMediaSysOS,
		/** media systemOverdubOrSubtitle overdub subtitle */
		EMediaSysOverCap,
		/** media systemRequired */
		EMediaSysReq,
		/** media systemScreenDepth */
		EMediaSysScrnDepth,
		/** media systemScreenSize */
		EMediaSysScrnSize,
		/** media title */
		EMediaTitle,
		/** media transIn */
		EMediaTransIn,
		/** media transOut */
		EMediaTransOut,
		/** media type */
		EMediaType,
		/** media xml:lang */
		EMediaXMLLang,
		/** meta class */
		EMetaClass,
		/** meta content */
		EMetaContent,
		/** meta id */
		EMetaId,
		/** meta name */
		EMetaName,
		/** meta skip-content false true */
		EMetaSkipContent,
		/** meta title */
		EMetaTitle,
		/** meta xml:lang */
		EMetaXMLLang,
		/** metadata class */
		EMetadataClass,
		/** metadata id */
		EMetadataId,
		/** metadata skip-content false true */
		EMetadataSkipContent,
		/** metadata title */
		EMetadataTitle,
		/** metadata xml:lang */
		EMetadataXMLLang,
		/** prefetch bandwidth */
		EPrefetchBandwith,
		/** prefetch class */
		EPrefetchClass,
		/** prefetch id */
		EPrefetchId,
		/** prefetch mediaSize */
		EPrefetchMediaSize,
		/** prefetch mediaTime */
		EPrefetchMediaTime,
		/** prefetch skip-content false true */
		EPrefetchSkipContent,
		/** prefetch src */
		EPrefetchSrc,
		/** prefetch systemAudioDesc off on */
		EPrefetchSysAudioDesc,
		/** prefetch systemBitrate */
		EPrefetchSysBitrate,
		/** prefetch systemCPU */
		EPrefetchSysCPU,
		/** prefetch systemCaptions off on */
		EPrefetchSysCaptions,
		/** prefetch systemComponent */
		EPrefetchSysComp,
		/** prefetch systemLanguage */
		EPrefetchSysLang,
		/** prefetch systemOperatingSystem */
		EPrefetchSysOS,
		/** prefetch systemOverdubOrSubtitle */
		EPrefetchSysOvrdubSub,
		/** prefetch systemRequired */
		EPrefetchSysRequired,
		/** prefetch systemScreenDepth */
		EPrefetchSysScrnDepth,
		/** prefetch systemScreenSize */
		EPrefetchSysScrnSize,
		/** prefetch title */
		EPrefetchTitle,
		/** prefetch xml:lang */
		EPrefetchXMLLang,
		/** region background-color */
		ERegionBGHypCol,
		/** region backgroundColor */
		ERegionBGCol,
		/** region bottom */
		ERegionBottom,
		/** region class */
		ERegionClass,
		/** region close never whenNotActive */
		ERegionClose,
		/** region fit fill hidden meet scroll slice */
		ERegionFit,
		/** region height */
		ERegionHeight,
		/** region id */
		ERegionId,
		/** region left */
		ERegionLeft,
		/** region open always whenActive */
		ERegionOpen,
		/** region regionName */
		ERegionRegionName,
		/** region right */
		ERegionRight,
		/** region showBackground always whenActive */
		ERegionShowBG,
		/** region skip-content false true */
		ERegionSkipContent,
		/** region title */
		ERegionTitle,
		/** region top */
		ERegionTop,
		/** region width */
		ERegionWidth,
		/** region xml:lang */
		ERegionXMLLang,
		/** region z-index */
		ERegionZIndex,
		/** root-layout background-color */
		ERootLayoutBGHypCol,
		/** root-layout backgroundColor */
		ERootLayoutBGCol,
		/** root-layout class */
		ERootLayoutClass,
		/** root-layout close never whenNotActive */
		ERootLayoutClose,
		/** root-layout height */
		ERootLayoutHeight,
		/** root-layout id */
		ERootLayoutId,
		/** root-layout open always whenActive */
		ERootLayoutOpen,
		/** root-layout skip-content false true */
		ERootLayoutSkipContent,
		/** root-layout title */
		ERootLayoutTitle,
		/** root-layout width */
		ERootLayoutWidth,
		/** root-layout xml:lang */
		ERootLayoutXMLLang,
		/** smil class */
		ESMILClass,
		/** smil id */
		ESMILId,
		/** smil systemAudioDesc off on */
		ESMILSysAudioDesc,
		/** smil systemBitrate */
		ESMILSysBitrate,
		/** smil systemCPU */
		ESMILSysCPU,
		/** smil systemCaptions off on */
		ESMILSysCaptions,
		/** smil systemComponent */
		ESMILSysComp,
		/** smil systemLanguage */
		ESMILSysLang,
		/** smil systemOperatingSystem */
		ESMILSysOS,
		/** smil systemOverdubOrSubtitle overdub subtitle */
		ESMILSysOverCap,
		/** smil systemRequired */
		ESMILSysReq,
		/** smil systemScreenDepth */
		ESMILSysScrnDepth,
		/** smil systemScreenSize */
		ESMILSysScrnSize,
		/** smil title */
		ESMILTitle,
		/** smil xml:lang */
		ESMILXMLLang,
		/** smil xmlns */
		ESMILXMLNS,
		/** switch class */
		ESwitchClass,
		/** switch id */
		ESwitchId,
		/** switch systemAudioDesc off on */
		ESwitchSysAudioDesc,
		/** switch systemBitrate */
		ESwitchSysBitrate,
		/** switch systemCPU */
		ESwitchSysCPU,
		/** switch systemCaptions off on */
		ESwitchSysCaptions,
		/** switch systemComponent */
		ESwitchSysComp,
		/** switch systemLanguage */
		ESwitchSysLang,
		/** switch systemOperatingSystem */
		ESwitchSysOS,
		/** switch systemOverdubOrSubtitle overdub subtitle */
		ESwitchSysOverCap,
		/** switch systemRequired */
		ESwitchSysReq,
		/** switch systemScreenDepth */
		ESwitchSysScrnDepth,
		/** switch systemScreenSize */
		ESwitchSysScrnSize,
		/** switch title */
		ESwitchTitle,
		/** switch xml:lang */
		ESwitchXMLLang,
		/** timing abstract */
		ETimingAbstract,
		/** timing author */
		ETimingAuthor,
		/** timing begin */
		ETimingBegin,
		/** timing class */
		ETimingClass,
		/** timing copyright */
		ETimingCopyright,
		/** timing customTest */
		ETimingCustomTest,
		/** timing dur */
		ETimingDur,
		/** timing end */
		ETimingEnd,
		/** timing endsync */
		ETimingEndSync,
		/** timing fill freeze hold remove transition */
		ETimingFill,
		/** timing id */
		ETimingId,
		/** timing max */
		ETimingMax,
		/** timing min */
		ETimingMin,
		/** timing repeat */
		ETimingRepeat,
		/** timing repeatCount */
		ETimingRepeatCount,
		/** timing repeatDur */
		ETimingRepeatDur,
		/** timing system-bitrate */
		ETimingSysHypBitRate,
		/** timing system-captions on off */
		ETimingSysHypCaptions,
		/** timing system-language */
		ETimingSysHypLang,
		/** timing system-overdub-or-caption caption overdub */
		ETimingSysHypOverCap,
		/** timing system-required */
		ETimingSysHypReq,
		/** timing system-screen-depth */
		ETimingSysHypScrnDepth,
		/** timing system-screen-size */
		ETimingSysHypScrnSize,
		/** timing systemAudioDesc off on */
		ETimingSysAudioDesc,
		/** timing systemBitrate */
		ETimingSysBitrate,
		/** timing systemCPU */
		ETimingSysCPU,
		/** timing systemCaptions off on */
		ETimingSysCaptions,
		/** timing systemComponent */
		ETimingSysComp,
		/** timing systemLanguage */
		ETimingSysLang,
		/** timing systemOperatingSystem */
		ETimingSysOS,
		/** timing systemOverdubOrSubtitle */
		ETimingSysOverdubSub,
		/** timing systemRequired */
		ETimingSysReq,
		/** timing systemScreenDepth */
		ETimingSysScrnDepth,
		/** timing systemScreenSize */
		ETimingSysScrnSize,
		/** timing title */
		ETimingTitle,
		/** timing xml:lang */
		ETimingXMLLAng,
		/** transition class */
		ETransitionClass,
		/** transition direction forward reverse */
		ETransitionDirecton,
		/** transition dur */
		ETransitionDur,
		/** transition endProgress */
		ETransitionEndProg,
		/** transition fadeColor */
		ETransitionFadeCol,
		/** transition id */
		ETransitionId,
		/** transition skip-content false true */
		ETransitionSkipContent,
		/** transition startProgress */
		ETransitionStartProg,
		/** transition subtype */
		ETransitionSubtype,
		/** transition systemAudioDesc off on */
		ETransitionSysAudioDesc,
		/** transition systemBitrate */
		ETransitionSysBitrate,
		/** transition systemCPU */
		ETransitionSysCPU,
		/** transition systemCaptions off on */
		ETransitionSysCaptions,
		/** transition systemComponent */
		ETransitionSysComp,
		/** transition systemLanguage */
		ETransitionSysLang,
		/** transition systemOperatingSystem */
		ETransitionSysOS,
		/** transition systemOverdubOrSubtitle */
		ETransitionSysOvrdubSub,
		/** transition systemRequired */
		ETransitionSysRequired,
		/** transition systemScreenDepth */
		ETransitionSysScrnDepth,
		/** transition systemScreenSize */
		ETransitionSysScrnSize,
		/** transition title */
		ETransitionTitle,
		/** transition type */
		ETransitionType,
		/** transition xml:lang */
		ETransitionXMLLang
		};
	static const TStringTable Table;	
	};

#endif // STRINGTABLE_SMILAttributes

