// Autogenerated from epoc32/build/legacyminidomparser/c_212b04b63d6cae98/xmlparser_dll/xmlentityreferences.st by the stringtable tool - Do not edit

#ifndef STRINGTABLE_XMLEntityReferences
#define STRINGTABLE_XMLEntityReferences

#include <stringpool.h>

struct TStringTable;

/** A String table */
class XMLEntityReferences 
	{
public:
	enum TStrings
		{
		/** &lt; < */
		ELT,
		/** &amp; & */
		EAmp,
		/** &gt; > */
		EGt,
		/** &quot; \" */
		EDbleQuote,
		/** &apos; ' */
		ESingleQuote
		};
	static const TStringTable Table;	
	};

#endif // STRINGTABLE_XMLEntityReferences

